#!/bin/bash
# Script to automatically fix no-unused-vars ESLint errors
# Generated by Claude Code based on Gemini's correction pattern

set -e

echo "🔧 Fixing ESLint no-unused-vars errors..."

# Backup directory
BACKUP_DIR="/tmp/archon-lint-backup-$(date +%s)"
mkdir -p "$BACKUP_DIR"

# Function to backup and fix a file
fix_file() {
    local file="$1"
    shift
    local patterns=("$@")

    if [ ! -f "$file" ]; then
        echo "⚠️  File not found: $file"
        return
    fi

    # Backup
    cp "$file" "$BACKUP_DIR/$(basename $file)"

    # Apply fixes
    for pattern in "${patterns[@]}"; do
        sed -i.bak "$pattern" "$file"
        rm -f "${file}.bak"
    done

    echo "✅ Fixed: $file"
}

# Fix src/agents/registry.js
fix_file "src/agents/registry.js" \
    "s/import { wait }/\/\/ import { wait } - unused/"

# Fix src/agents/sub-agents/specialized-agents.js (multiple patterns)
fix_file "src/agents/sub-agents/specialized-agents.js" \
    "s/async _implementState(requirements, context)/async _implementState(_requirements, _context)/" \
    "s/async _implementValidation(requirements, context)/async _implementValidation(_requirements, _context)/" \
    "s/async _setupEnvironment(context)/async _setupEnvironment(_context)/" \
    "s/async _implementAuth(context)/async _implementAuth(_context)/" \
    "s/async _setupDatabase(context)/async _setupDatabase(_context)/" \
    "s/async _createAPI(requirements, context)/async _createAPI(_requirements, _context)/" \
    "s/async _setupInfrastructure(requirements, context)/async _setupInfrastructure(_requirements, _context)/" \
    "s/async _createTest(context)/async _createTest(_context)/" \
    "s/async _runTests(requirements, context)/async _runTests(_requirements, _context)/" \
    "s/async _setupCI(requirements, context)/async _setupCI(_requirements, _context)/" \
    "s/async _generateDocs(requirements, context)/async _generateDocs(_requirements, _context)/" \
    "s/async _setupMonitoring(requirements, context)/async _setupMonitoring(_requirements, _context)/" \
    "s/async _optimizeBundle(requirements, context)/async _optimizeBundle(_requirements, _context)/" \
    "s/async _implementCaching(context)/async _implementCaching(_context)/" \
    "s/async _setupAnalytics(requirements, context)/async _setupAnalytics(_requirements, _context)/" \
    "s/async _setupSecurity(requirements, context)/async _setupSecurity(_requirements, _context)/" \
    "s/async _analyzeCode(context)/async _analyzeCode(_context)/" \
    "s/const { config } = params;/const { config: _config } = params;/" \
    "s/const \[agentId\] = /const \[_agentId\] = /"

# Fix src/architecture-compliance/context-injection.js
fix_file "src/architecture-compliance/context-injection.js" \
    "s/} catch (error) {/} catch (_error) {/" \
    "s/async injectProjectContext(projectPath)/async injectProjectContext(_projectPath)/" \
    "s/generateTaskContext(agentType, taskDescription)/generateTaskContext(_agentType, _taskDescription)/"

# Fix src/architecture-compliance/index.js
fix_file "src/architecture-compliance/index.js" \
    "s/const logger = /\/\/ const logger = /" \
    "s/async function applyQualityGates(code, architectureContext, options)/async function applyQualityGates(code, architectureContext, _options)/"

# Fix src/architecture-compliance/quality-gates.js
fix_file "src/architecture-compliance/quality-gates.js" \
    "s/import { promises as fs } from 'fs';/\/\/ import { promises as fs } from 'fs'; - unused/" \
    "s/import path from 'path';/\/\/ import path from 'path'; - unused/" \
    "s/const content = /\/\/ const content = /" \
    "s/checkLayerViolations(code, architectureContext)/checkLayerViolations(code, _architectureContext)/" \
    "s/validateModuleBoundaries(code, architectureContext)/validateModuleBoundaries(code, _architectureContext)/" \
    "s/validateFileStructure(code, structure)/validateFileStructure(code, _structure)/" \
    "s/validateNamingConventions(code, namingConventions)/validateNamingConventions(code, _namingConventions)/" \
    "s/enforceGate(code, architectureContext, agentType, gate)/enforceGate(code, _architectureContext, _agentType, _gate)/" \
    "s/async function injectContextBeforeTask(task, architectureContext, agentType, gate)/async function injectContextBeforeTask(task, _architectureContext, _agentType, _gate)/" \
    "s/async function validateAfterTask(result, architectureContext, agentType, gate)/async function validateAfterTask(result, _architectureContext, _agentType, _gate)/" \
    "s/function generateComplianceReport(injectionId)/function generateComplianceReport(_injectionId)/"

# Fix src/architecture-compliance/validation-pipeline.js
fix_file "src/architecture-compliance/validation-pipeline.js" \
    "s/const architectureContext = /\/\/ const architectureContext = /"

# Fix src/gdpr-compliance/audit-trail-system.js
fix_file "src/gdpr-compliance/audit-trail-system.js" \
    "s/const merkleRoot = /\/\/ const merkleRoot = /" \
    "s/const encryptExport = /\/\/ const encryptExport = /" \
    "s/const now = Date.now();/\/\/ const now = Date.now(); - unused/"

# Fix src/gdpr-compliance/consent-manager.js
fix_file "src/gdpr-compliance/consent-manager.js" \
    "s/async recordConsent(userId, purposes, ipAddress)/async recordConsent(userId, purposes, _ipAddress)/" \
    "s/_encryptData(data) {/_encryptData(_data) {/" \
    "s/_decryptData(data) {/_decryptData(_data) {/"

# Fix src/gdpr-compliance/data-processor.js (many userId)
fix_file "src/gdpr-compliance/data-processor.js" \
    "s/async requestDataExport(userId) {/async requestDataExport(_userId) {/" \
    "s/_encryptData(data) {/_encryptData(_data) {/" \
    "s/_decryptData(data) {/_decryptData(_data) {/" \
    "s/const now = Date.now();/\/\/ const now = Date.now(); - unused/" \
    "s/} catch (error) {/} catch (_error) {/" \
    "s/const dataSource = /\/\/ const dataSource = /" \
    "s/async anonymizeUser(userId)/async anonymizeUser(_userId)/" \
    "s/async pseudonymizeUser(userId)/async pseudonymizeUser(_userId)/" \
    "s/async hashUser(userId)/async hashUser(_userId)/" \
    "s/async encryptUserData(userId)/async encryptUserData(_userId)/" \
    "s/async maskEmail(userId)/async maskEmail(_userId)/" \
    "s/async maskPhone(userId)/async maskPhone(_userId)/" \
    "s/async removeIdentifiers(userId)/async removeIdentifiers(_userId)/" \
    "s/async aggregateData(userId)/async aggregateData(_userId)/" \
    "s/async generalize(userId)/async generalize(_userId)/" \
    "s/async suppress(userId)/async suppress(_userId)/" \
    "s/async perturb(userId)/async perturb(_userId)/" \
    "s/async swap(userId)/async swap(_userId)/"

# Fix src/gdpr-compliance/gdpr-validator.js
fix_file "src/gdpr-compliance/gdpr-validator.js" \
    "s/import { legalDocumentsGenerator }/\/\/ import { legalDocumentsGenerator } - unused/"

# Fix src/gdpr-compliance/index.js
fix_file "src/gdpr-compliance/index.js" \
    "s/async function complianceCheck(system)/async function complianceCheck(_system)/"

# Fix src/http-adapter.js
fix_file "src/http-adapter.js" \
    "s/import { v4 as uuidv4 }/\/\/ import { v4 as uuidv4 } - unused/"

# Fix src/integrations/github-mcp-client.js
fix_file "src/integrations/github-mcp-client.js" \
    "s/} catch (e) {/} catch (_e) {/"

# Fix src/lighthouse-server.js
fix_file "src/lighthouse-server.js" \
    "s/app.use((err, req, res, next)/app.use((err, req, res, _next)/"

# Fix src/mcp/claude-code-orchestration-tools.js
fix_file "src/mcp/claude-code-orchestration-tools.js" \
    "s/} catch (error) {/} catch (_error) {/" \
    "s/async handleInitialize(args)/async handleInitialize(_args)/" \
    "s/async handleShutdown(args)/async handleShutdown(_args)/" \
    "s/async handleResourcesList(args)/async handleResourcesList(_args)/" \
    "s/async handleResourcesRead(args)/async handleResourcesRead(_args)/" \
    "s/async handlePromptsList(args)/async handlePromptsList(_args)/" \
    "s/async handleToolsCall(args)/async handleToolsCall(_args)/"

# Fix src/mcp/server.js
fix_file "src/mcp/server.js" \
    "s/import WebSocket from 'ws';/\/\/ import WebSocket from 'ws'; - unused/"

# Fix src/mcp/start-server.js
fix_file "src/mcp/start-server.js" \
    "s/const server = /\/\/ const server = /"

# Fix src/mcp/tools.js (multiple destructured variables)
fix_file "src/mcp/tools.js" \
    "s/deadline, team_size/_deadline, _team_size/g" \
    "s/exploration_depth/_exploration_depth/" \
    "s/validation_focus/_validation_focus/" \
    "s/parallel_execution/_parallel_execution/"

# Fix src/orchestrator/context-manager.js
fix_file "src/orchestrator/context-manager.js" \
    "s/} catch (error) {/} catch (_error) {/g"

# Fix src/orchestrator/metrics.js
fix_file "src/orchestrator/metrics.js" \
    "s/} catch (error) {/} catch (_error) {/"

# Fix src/orchestrator/multi-task-orchestrator.cjs
fix_file "src/orchestrator/multi-task-orchestrator.cjs" \
    "s/async function createTaskPlan(architecture, requirements, plan)/async function createTaskPlan(_architecture, _requirements, _plan)/"

# Fix src/orchestrator/router.js
fix_file "src/orchestrator/router.js" \
    "s/const context = /\/\/ const context = /" \
    "s/function selectAgentForTask(task, complexity)/function selectAgentForTask(task, _complexity)/" \
    "s/} catch (error) {/} catch (_error) {/"

# Fix src/services/context-service.js
fix_file "src/services/context-service.js" \
    "s/async analyzeFile(content, filePath)/async analyzeFile(content, _filePath)/g" \
    "s/getRelevantContext(query, extension)/getRelevantContext(query, _extension)/" \
    "s/addTaskContext(contextId, task)/addTaskContext(contextId, _task)/"

# Fix src/sub-agent-orchestrator.js
fix_file "src/sub-agent-orchestrator.js" \
    "s/projectContext, previousResults/_projectContext, _previousResults/g"

echo ""
echo "✅ All fixes applied!"
echo "📋 Backup location: $BACKUP_DIR"
echo ""
echo "🔍 Running lint validation..."

if pnpm lint; then
    echo ""
    echo "🎉 SUCCESS! All lint errors fixed!"
    echo "🗑️  You can safely delete backup: rm -rf $BACKUP_DIR"
    exit 0
else
    echo ""
    echo "❌ FAILED! Restoring backup..."
    # Restore backup
    for backup in "$BACKUP_DIR"/*; do
        filename=$(basename "$backup")
        find . -name "$filename" -type f -exec cp "$backup" {} \;
    done
    echo "⚠️  Backup restored. Manual fixing required."
    exit 1
fi
